name: Update

on:
  push:
  schedule:
    - cron: 0 16 * * *

env:
  TZ: Asia/Shanghai

jobs:
  Update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: GetTime
      run: echo "GET_TIME=$(date +'%Y-%m-%d %H:%M:%S CST')" >> $GITHUB_ENV

    - name: Update
      run: |
        rm -f dnsproxy
        DNSPROXY_LATEST=$(curl -s https://api.github.com/repos/AdguardTeam/dnsproxy/releases/latest \
            | grep tag_name \
            | cut -d ":" -f2 \
            | sed 's/\"//g;s/\,//g;s/\ //g;s/v//')
        curl -LOf# https://github.com/AdguardTeam/dnsproxy/releases/download/v${DNSPROXY_LATEST}/dnsproxy-linux-amd64-v${DNSPROXY_LATEST}.tar.gz
        tar -zxvf dnsproxy-linux-amd64-v${DNSPROXY_LATEST}.tar.gz ./linux-amd64/dnsproxy
        rm -f dnsproxy-linux-amd64-v${DNSPROXY_LATEST}.tar.gz
        mv linux-amd64/dnsproxy dnsproxy
        rm -rf linux-amd64
        echo "Auto Update DNSProxy(${DNSPROXY_LATEST}) in ${GET_TIME}" > README.md

    - name: Clean
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git checkout --orphan latest_branch
        git add -A
        git commit -am "${GET_TIME}"
        git branch -D Files
        git branch -m Files

    - name: Push
      run: git push -f origin Files
